name: TurnTest

on:
  push:
    branches: ["Lab_1_Task_2_Ovsyannikov"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore SpaceBattle

      - name: Test Build
        run: dotnet build SpaceBattle.Lib --no-restore /p:ContinuousIntegrationBuild=true

      - name: Turn Test
        run: dotnet test SpaceBattle.Lib.Tests /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov