name: Lab1 straight-line movement

on:
  [workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore ./spacebattle/SpaceBattle.Lib

      - name: Build and format
        run: dotnet build ./spacebattle/SpaceBattle.Lib --no-restore /p:ContinuousIntegrationBuild=true && dotnet format

      - name: Test
        run: ./spacebattle/SpaceBattle.Lib.Tests ./spacebattle/SpaceBattle.Lib.Tests/bin/Debug/net7.0/SpaceBattle.Lib.Tests.dll

      - name: SpaceBattle test
        run: cd ./spacebattle/SpaceBattle.Lib.Tests/ && dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=json
